[package]
name = "grooph"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
either = "1.15.0"
log = "0.4.28"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.55"
web-sys = "0.3.82"

[lints.rust]
unused_imports = "allow"

[profile.release]
opt-level = 2 # fast and small wasm
