[package]
name = "grooph"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui_extras = { version = "0.33.2", features = ["svg"] }
either = "1.15.0"
log = "0.4.29"
rodio = { version = "0.21.1", features = ["playback", "noise"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.55"
web-sys = { version = "0.3.83", features = ["WakeLock", "WakeLockSentinel", "WakeLockType", "Window", "Navigator"] }
cpal = { version = "0.16.0", features = ["wasm-bindgen"] }
getrandom = { version = "0.3.3", features = ["wasm_js"] }

[lints.rust]
unused_imports = "allow"

[profile.release]
opt-level = "z"
lto = true

