[workspace]
resolver = "2"
members = [
    "crates/app",
    "crates/audio",
    "crates/layout",
    "crates/measure",
    "crates/midi",
    "crates/render",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["systemfreund"]
license = "LGPL-2"

[workspace.dependencies]
grooph-audio = { path = "crates/audio" }
grooph-layout = { path = "crates/layout" }
grooph-measure = { path = "crates/measure" }
grooph-midi = { path = "crates/midi" }
grooph-render = { path = "crates/render" }
cpal = { version = "0.16", features = ["wasm-bindgen"] }
eframe = { version = "0.34", features = ["persistence"] }
egui = "0.34"
egui_extras = { version = "0.34", features = ["image", "svg"] }
either = "1.15.0"
env_logger = "0.11.8"
getrandom = { version = "0.3.3", features = ["wasm_js"] }
log = "0.4.29"
midir = "0.10"
rodio = { version = "0.21", features = ["playback", "noise"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.56"
web-sys = { version = "0.3", features = ["Document", "Navigator", "VisibilityState", "WakeLock", "WakeLockSentinel", "WakeLockType", "Window"] }

[profile.release]
opt-level = "z"
lto = true
