[package]
name = "grooph-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
grooph-measure = { workspace = true }
grooph-layout = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }

[lints.rust]
unused_imports = "allow"
