[package]
name = "grooph-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
grooph-measure = { workspace = true }
grooph-audio = { workspace = true }
grooph-layout = { workspace = true }
grooph-render = { workspace = true }
eframe = { version = "0.33", features = ["persistence"] }
egui = "0.33"
egui_extras = { version = "0.33", features = ["image", "svg"] }
log = "0.4.29"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.56"
web-sys = { version = "0.3", features = ["Document", "Navigator", "VisibilityState", "WakeLock", "WakeLockSentinel", "WakeLockType", "Window"] }
getrandom = { version = "0.3.3", features = ["wasm_js"] }

[lints.rust]
unused_imports = "allow"
