[package]
name = "grooph-audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
grooph-measure = { workspace = true }
log = { workspace = true }
rodio = { workspace = true }
serde = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { workspace = true }

[lints.rust]
unused_imports = "allow"
